title: 虽不能至，心向往之
author: Yongfei	
email: h739578083@gmail.com	
description: > # this means to ignore newlines until "baseurl:"	
  社区文化：读书，健身，投资，帮朋友，陪家人
 


show_excerpts: false # set to false to remove excerpts on the homepage

  
theme: jekyll-theme-slate
