title: 我要便匆名--向查理致敬！
author: Yongfei
email: h739578083@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  定投践行群108班成员
  社区文化：读书，健身，投资，帮朋友，陪家人
 


show_excerpts: true # set to false to remove excerpts on the homepage

  
theme: jekyll-theme-slate
